;/*FB_PKG_DELIM*/

__d("CometGroupAnnouncementsRootFeedQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="6504599806241160"}),null);
__d("CometGroupAnnouncementsRootFeedQuery$Parameters",["CometGroupAnnouncementsRootFeedQuery_facebookRelayOperation","GroupsCometDelayCheckBlockedUsers.relayprovider","GroupsCometGroupChatLazyLoadLastMessageSnippet.relayprovider","GroupsCometHasLeftRailNavImprovement.relayprovider","IsMergQAPolls.relayprovider","IsWorkUser.relayprovider","StoriesArmadilloReplyEnabled.relayprovider","StoriesRing.relayprovider"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometGroupAnnouncementsRootFeedQuery_facebookRelayOperation"),metadata:{},name:"CometGroupAnnouncementsRootFeedQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__GroupsCometDelayCheckBlockedUsersrelayprovider:b("GroupsCometDelayCheckBlockedUsers.relayprovider"),__relay_internal__pv__IsWorkUserrelayprovider:b("IsWorkUser.relayprovider"),__relay_internal__pv__IsMergQAPollsrelayprovider:b("IsMergQAPolls.relayprovider"),__relay_internal__pv__StoriesArmadilloReplyEnabledrelayprovider:b("StoriesArmadilloReplyEnabled.relayprovider"),__relay_internal__pv__StoriesRingrelayprovider:b("StoriesRing.relayprovider"),__relay_internal__pv__GroupsCometHasLeftRailNavImprovementrelayprovider:b("GroupsCometHasLeftRailNavImprovement.relayprovider"),__relay_internal__pv__GroupsCometGroupChatLazyLoadLastMessageSnippetrelayprovider:b("GroupsCometGroupChatLazyLoadLastMessageSnippet.relayprovider")}}};e.exports=a}),null);
__d("CometGroupEventsRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5907997009286453"}),null);
__d("CometGroupEventsRootQuery$Parameters",["CometGroupEventsRootQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometGroupEventsRootQuery_facebookRelayOperation"),metadata:{},name:"CometGroupEventsRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("GroupsCometFilesTabRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4926282924126140"}),null);
__d("GroupsCometFilesTabRootQuery$Parameters",["GroupsCometFilesTabRootQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("GroupsCometFilesTabRootQuery_facebookRelayOperation"),metadata:{},name:"GroupsCometFilesTabRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("GroupsCometPhotosRootQueryContainerQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="9518053834886608"}),null);
__d("GroupsCometPhotosRootQueryContainerQuery$Parameters",["GroupsCometPhotosRootQueryContainerQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("GroupsCometPhotosRootQueryContainerQuery_facebookRelayOperation"),metadata:{},name:"GroupsCometPhotosRootQueryContainerQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("GroupsCometMembersRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="6125529747525406"}),null);
__d("GroupsCometMembersRootQuery$Parameters",["GroupsCometMembersRootQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("GroupsCometMembersRootQuery_facebookRelayOperation"),metadata:{},name:"GroupsCometMembersRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("GroupsCometInfoCard.react",["CometCard.react","CometErrorBoundary.react","CometUnit.react","CometUnitHeader.react","TetraText.react","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react");function a(a){return h.jsx(c("CometErrorBoundary.react"),{children:h.jsx("div",{className:"x1yztbdb","data-testid":void 0,children:h.jsx(c("CometCard.react"),{background:"white",dropShadow:1,children:h.jsx("div",{className:"x1wsgfga",children:h.jsxs(c("CometUnit.react"),{header:h.jsx(c("CometUnitHeader.react"),{action:a.action,actiontestid:a.actiontestid,body:a.headerBody,headline:a.header,level:3,onActionPress:a.onActionPress}),children:[h.jsx("hr",{className:"x14nfmen xktsk01 x1d52u69 x14vqqas"}),a.children]})})})})})}a.displayName=a.name+" [from "+f.id+"]";a.Section=function(a){return h.jsxs(h.Fragment,{children:[h.jsx("div",{className:"xzueoph xhrpt6u x1pi30zi x1swvt13",children:h.jsx(c("TetraText.react"),{isSemanticHeading:!0,type:"bodyLink3",children:a.title})}),a.children]})};g["default"]=a}),98);
__d("GroupsCometResponsiveColumnsTabRoot.react",["react","stylex"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react"),i={adminToolsPageRoot:{width:"x1aody8q",$$css:!0},root:{alignSelf:"xamitd3",marginTop:"x1sy10c2",marginBottom:"xieb3on",maxWidth:"x193iq5w",minHeight:"xrljuej",$$css:!0}};function a(a){var b=a.children,d=a.isAdminToolsPageRoot;d=d===void 0?!1:d;a=a.testid;return h.jsx("div",{className:c("stylex")(i.root,d===!0&&i.adminToolsPageRoot),"data-testid":void 0,children:b})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("CometGroupAnnouncementsRoot.entrypointutils",["WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";function a(a){a=a.routeProps;var b=a.canSeeHighlightsSection;a=a.groupID;return{feedbackSource:0,feedLocation:"GROUP_ANNOUNCEMENTS_FEED",focusCommentID:null,groupID:a,orderby:b===!0?[]:["is_pinned","most_recent"],privacySelectorRenderLocation:"COMET_STREAM",renderLocation:"group",scale:d("WebPixelRatio").get()}}g.getGroupCometAnnouncementsRootVariables=a}),98);
__d("CometGroupAnnouncementsRoot.entrypoint",["CometGroupAnnouncementsRoot.entrypointutils","CometGroupAnnouncementsRootFeedQuery$Parameters","JSResourceForInteraction","buildGroupCometRootRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildGroupCometRootRoute.entrypoint")(c("JSResourceForInteraction")("CometGroupAnnouncementsRoot.react").__setRef("CometGroupAnnouncementsRoot.entrypoint"),function(a){return{queries:{queryReference:{parameters:b("CometGroupAnnouncementsRootFeedQuery$Parameters"),variables:babelHelpers["extends"]({},d("CometGroupAnnouncementsRoot.entrypointutils").getGroupCometAnnouncementsRootVariables(a))}}}});g["default"]=a}),98);
__d("CometGroupEventsRoot.entrypoint",["CometGroupEventsRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildGroupCometRootRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";var h=3;a=c("buildGroupCometRootRoute.entrypoint")(c("JSResourceForInteraction")("CometGroupEventsRoot.react").__setRef("CometGroupEventsRoot.entrypoint"),function(a){a=a.routeProps;a=a.groupID;a={count:h,groupID:a,scale:d("WebPixelRatio").get()};return{queries:{queryReference:{parameters:b("CometGroupEventsRootQuery$Parameters"),variables:a}}}});g["default"]=a}),98);
__d("GroupsCometFilesTabRoot.entrypoint",["GroupsCometFilesTabRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildGroupCometRootRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildGroupCometRootRoute.entrypoint")(c("JSResourceForInteraction")("GroupsCometFilesTabRoot.react").__setRef("GroupsCometFilesTabRoot.entrypoint"),function(a){a=a.routeProps;a=a.groupID;return{queries:{queryReference:{parameters:b("GroupsCometFilesTabRootQuery$Parameters"),variables:{groupDocsFileName:null,groupID:a,orderby:null,scale:d("WebPixelRatio").get()}}}}});g["default"]=a}),98);
__d("GroupsCometPhotosRootQueryVariables",[],(function(a,b,c,d,e,f){"use strict";a=8;f.count=a}),66);
__d("GroupsCometPhotosRoot.entrypoint",["GroupsCometPhotosRootQueryContainerQuery$Parameters","GroupsCometPhotosRootQueryVariables","JSResourceForInteraction","WebPixelRatio","buildGroupCometRootRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildGroupCometRootRoute.entrypoint")(c("JSResourceForInteraction")("GroupsCometPhotosRoot.react").__setRef("GroupsCometPhotosRoot.entrypoint"),function(a){a=a.routeProps;var c=a.extraSections;a=a.groupID;return{extraProps:{extraSections:c},queries:{queryReference:{parameters:b("GroupsCometPhotosRootQueryContainerQuery$Parameters"),variables:babelHelpers["extends"]({groupID:a,scale:d("WebPixelRatio").get()},d("GroupsCometPhotosRootQueryVariables"))}}}});g["default"]=a}),98);
__d("GroupsCometMembersRoot.entrypoint",["GroupsCometMembersRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildGroupCometRootRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildGroupCometRootRoute.entrypoint")(c("JSResourceForInteraction")("GroupsCometMembersRoot.react").__setRef("GroupsCometMembersRoot.entrypoint"),function(a){var c=a.routeParams;a=a.routeProps;a=a.groupID;c=c.only_recruiting_group_non_compliant;a={groupID:a,recruitingGroupFilterNonCompliant:c,scale:d("WebPixelRatio").get()};return{queries:{queryReference:{parameters:b("GroupsCometMembersRootQuery$Parameters"),variables:a}}}});g["default"]=a}),98);