;/*FB_PKG_DELIM*/

__d("NullStateLists",["cr:3212"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:3212")}),98);
__d("NullStateListsFB",["IconSource"],(function(a,b,c,d,e,f,g){"use strict";a={dark:new(c("IconSource"))("nullStateGlyphs","/images/comet/empty_states_icons/lists/null_states_list_dark_mode.svg",112),"default":new(c("IconSource"))("nullStateGlyphs","/images/comet/empty_states_icons/lists/null_states_list_gray_wash.svg",112)};g["default"]=a}),98);
__d("createUseMutation_DEPRECATED",["CometRelay","Promise","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useCallback;function a(a,c,e,f){return function(){var g=d("CometRelay").useRelayEnvironment();return h(function(h,i,j){return new(b("Promise"))(function(b,k){return d("CometRelay").enqueueMutation(g,{mutation:a,onCompleted:function(a,c){c&&c.length?k(c):b(a)},onError:function(a){return k([a])},optimisticResponse:c?c(h,i,j):null,optimisticUpdater:e?e(h,i,j):null,updater:f?f(h,i,j):null,variables:babelHelpers["extends"]({input:h},i)})})},[g])}}g["default"]=a}),98);
__d("ABTestingPostVariantType",["$InternalEnum"],(function(a,b,c,d,e,f){"use strict";a=b("$InternalEnum").Mirrored(["THUMBNAIL","TITLE"]);c=a;f["default"]=c}),66);
__d("CometComposerPushedPageOnLoad",[],(function(a,b,c,d,e,f){a=Object.freeze({ASK_FOR_RECOMMENDATIONS:"ask_for_recommendations",ASK_ME_ANYTHING:"ask_me_anything",COMMUNITY_QA:"community_qa",CONNECT_WHATSAPP:"connect_whatsapp",FEELING:"feeling",FUNDRAISER:"fundraiser",GET_MESSAGES:"get_messages",GET_WHATSAPP_MESSAGES:"get_whatsapp_messages",LOCAL_ALERT_TAGGER:"local_alert_tagger",LOCATION_TAGGER:"location_tagger",LOOKING_FOR_PLAYERS:"looking_for_players",MLE:"mle",PHOTO_VIDEO:"photo_video",PRAYER:"prayer",PRODUCT_TAGGER:"product_tagger",QUILTS_COMPOSER:"quilts_composer",SHARE_CANDIDATE:"share_candidate",SHIFT_COVER:"shift_cover",SHIFT_MANAGEMENT_COVER:"shift_management_cover",VIDEO_MEETUP:"video_meetup",VIDEO_PICKER:"video_picker",VOTING_ALERT_TAGGER:"voting_alert_tagger",WITH_TAGGER:"with_tagger"});f["default"]=a}),66);
__d("XCometLWIPostCreationControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/ad_center/create/boostpost/",Object.freeze({show_switched_toast:!1,show_coupon_interstitial_dialog:!1}),void 0);b=a;g["default"]=b}),98);
__d("PrivacyMutationSourceIDContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=null;c=a.createContext(b);g["default"]=c}),98);
__d("PrivacyMutationToken",["Base64","PrivacyMutationSourceIDContext","react"],(function(a,b,c,d,e,f,g){"use strict";b=d("react");var h=b.useContext,i=b.useMemo;function a(){var a=h(c("PrivacyMutationSourceIDContext"));return i(function(){return j(a)},[a])}function j(a){return a==null?null:c("Base64").encode(JSON.stringify({callsite_id:a,creation_time:Date.now(),type:0}))}g.usePrivacyMutationToken=a;g.getPrivacyMutationTokenFromSourceID=j}),98);
__d("GroupsCometChatsBlockedUsersInChatWarningViewerThreadDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4441460415958655"}),null);