;/*FB_PKG_DELIM*/

__d("useCometGlobalPanelShortcutsImage_bookmark.graphql",[],(function(a,b,c,d,e,f){"use strict";a=function(){var a={kind:"Variable",name:"scale",variableName:"scale"},b=[{kind:"Literal",name:"icon_size",value:"DP36"},a],c=[{alias:null,args:null,kind:"ScalarField",name:"uri",storageKey:null}];return{argumentDefinitions:[{kind:"RootArgument",name:"scale"}],kind:"Fragment",metadata:null,name:"useCometGlobalPanelShortcutsImage_bookmark",selections:[{alias:null,args:b,concreteType:"Image",kind:"LinkedField",name:"event_date_icon_image",plural:!1,selections:c,storageKey:null},{alias:null,args:b,concreteType:"Image",kind:"LinkedField",name:"bookmark_icon_image",plural:!1,selections:c,storageKey:null},{alias:null,args:[{kind:"Literal",name:"height",value:36},{kind:"Literal",name:"icon_style",value:"CASPIAN"},a,{kind:"Literal",name:"width",value:36}],concreteType:"Image",kind:"LinkedField",name:"image",plural:!1,selections:c,storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"section",storageKey:null}],type:"Bookmark",abstractKey:null}}();e.exports=a}),null);
__d("CometGlobalPanelPopoverPanel.react",["CometLeftRailShadow.react","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react");function a(a){a=a.children;return h.jsxs("div",{className:"x1jx94hy xat3117",children:[a,h.jsx("div",{className:"x1vtvx1t x1ey2m1c x10l6tqk x13vifvy x1i1rx1s"}),h.jsx(c("CometLeftRailShadow.react"),{})]})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("XCometHomeControllerParamsRefineValidator",["coerceRouteParams","refine"],(function(a,b,c,d,e,f,g){b=d("refine").or(d("refine").literal(null),d("refine").string());e=d("refine").object({filter:b,funnel_id:b,medium:b,ref:b,sk:b,story_graphql_id:b,story_id:b,team_id:b});var h=d("refine").coercion(e),i=Object.freeze({filter:{legacyNames:[],"default":null,coercibleType:"STRING"},sk:{legacyNames:[],"default":null,coercibleType:"STRING"},ref:{legacyNames:[],"default":null,coercibleType:"STRING"},story_id:{legacyNames:[],"default":null,coercibleType:"STRING"},medium:{legacyNames:[],"default":null,coercibleType:"STRING"},story_graphql_id:{legacyNames:[],"default":null,coercibleType:"STRING"},funnel_id:{legacyNames:[],"default":null,coercibleType:"STRING"},team_id:{legacyNames:[],"default":null,coercibleType:"STRING"}});function a(a){return h(c("coerceRouteParams")(a,i))}g.XCometHomeControllerParamsRefineValidator=a}),98);
__d("useCometGlobalPanelCoerceProductID",["CometRouteParams","RelayHooks","XCometHomeControllerParamsRefineValidator","gkx","useTopMostRouteCometEntityKey"],(function(a,b,c,d,e,f,g){"use strict";var h="513746992167374",i="285571681929755",j="4748854339",k="608920319153834",l="247654773079642",m="156203961126022",n="2356318349";function a(){var a=d("CometRouteParams").useCometRefinedRouteParams(d("XCometHomeControllerParamsRefineValidator").XCometHomeControllerParamsRefineValidator),b=(a=a==null?void 0:a.sk)!=null?a:void 0;a=c("useTopMostRouteCometEntityKey")();var e=d("RelayHooks").useActorID();a=(a==null?void 0:a.entity_type)==="profile"&&(a==null?void 0:a.entity_id)!==e;return a?function(){return n}:function(a){switch(a){case j:if(b==="favorites")return l;else if(b==="h_chr")return k;else if(b==="welcome")return m;return a;case i:return!c("gkx")("2042")?h:a;default:return a}}}g["default"]=a}),98);
__d("useCometGlobalPanelShortcutsImage",["CometIcon.react","CometProfilePhoto.react","CometRelay","ImageIconSource","react","useCometGlobalPanelShortcutsImage_bookmark.graphql"],(function(a,b,c,d,e,f,g){"use strict";var h,i=d("react");function a(a){var e=a.bookmark$key;a=a.size;e=d("CometRelay").useFragment(h!==void 0?h:h=b("useCometGlobalPanelShortcutsImage_bookmark.graphql"),e);var f=e.bookmark_icon_image,g=e.event_date_icon_image,j=e.image;e=e.section;if((j==null?void 0:j.uri)!=null)return i.jsx(c("CometProfilePhoto.react"),{shape:e==="USER"||e==="PAGE"?"circle":"roundedRect",size:a,source:{uri:j==null?void 0:j.uri}});else if(e==="EVENT"&&(g==null?void 0:g.uri)!=null)return i.jsx(c("CometIcon.react"),{icon:new(c("ImageIconSource"))(g==null?void 0:g.uri,a,a)});else if((f==null?void 0:f.uri)!=null)return i.jsx(c("CometIcon.react"),{icon:new(c("ImageIconSource"))(f==null?void 0:f.uri,a,a)});else return null}g["default"]=a}),98);
__d("useAppLastUsedTimestamps",["CometRelay","react","requireDeferred"],(function(a,b,c,d,e,f,g){"use strict";b=d("react");var h=b.useEffect,i=b.useState,j=c("requireDeferred")("AppLastUsedTimestampsFetcher").__setRef("useAppLastUsedTimestamps");function a(a){var b=i({}),c=b[0],e=b[1],f=d("CometRelay").useRelayEnvironment();h(function(){var b=null;j.onReady(function(c){b=c.fetch(f,a,e)});return function(){b!=null&&b.unsubscribe()}},[f,a]);return c}g["default"]=a}),98);
__d("XCometGroupsTabDiscoverControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/groups/discover/",Object.freeze({}),void 0);b=a;g["default"]=b}),98);
__d("XCometGroupsTabEngageControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/groups/feed/",Object.freeze({inline_composer_post:!1}),void 0);b=a;g["default"]=b}),98);
__d("GroupsCometNullState.react",["fbt","CometCard.react","NullStateMedia","NullStateNoResults","TetraButton.react","TetraNullState.react","XCometGroupsTabDiscoverControllerRouteBuilder","XCometGroupsTabEngageControllerRouteBuilder","react"],(function(a,b,c,d,e,f,g,h){"use strict";var i=d("react"),j=c("XCometGroupsTabDiscoverControllerRouteBuilder").buildURL({}),k=c("XCometGroupsTabEngageControllerRouteBuilder").buildURL({}),l=h._("__JHASH__KMFjEn2xtRV__JHASH__"),m=h._("__JHASH__NG6nLliU94j__JHASH__");function a(a){a=a.subTab;a=a!=="feed";return i.jsx("div",{className:"x1yztbdb",role:"article",children:i.jsx(c("CometCard.react"),{background:"white",dropShadow:1,children:i.jsx(c("TetraNullState.react"),{action:i.jsx(c("TetraButton.react"),{label:a?m:l,linkProps:{url:a?k:j}}),body:h._("__JHASH__K5Oe-W3kYnD__JHASH__"),headline:h._("__JHASH__XcMrMBe3VX0__JHASH__"),icon:a?c("NullStateNoResults"):c("NullStateMedia")})})})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("useGroupMarkPostsAsReadUpdate",["CometRelay","react","recoverableViolation"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useCallback;function a(){var a=d("CometRelay").useRelayEnvironment();return h(function(b){if(b==null){c("recoverableViolation")("Group null for left rail item","groups_comet");return}a.commitUpdate(function(a){a=a.get(b);a!=null&&(a.setValue(0,"unread_count"),a.setValue(!1,"should_show_community_panel_badge"))})},[a])}g["default"]=a}),98);
__d("CometGlobalPanelGroupPopoverQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="8163043347100491"}),null);
__d("CometGlobalPanelShortcutsPopoverQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5800715983292051"}),null);
__d("translatedServerString",[],(function(a,b,c,d,e,f){"use strict";function a(a){return a}f["default"]=a}),66);